version: '3.10'

services:
  web:
    image: "competencias_backend:dev"
    container_name: web
    build:
      target: development_build
      context: .
      cache_from:
        - "competencias_backend:dev"
        - "competencias_backend:latest"
      args:
        DJANGO_ENV: development
    command: python -Wd manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./aplicacao:/code/aplicacao
      - ./dominio:/code/dominio
      - ./competencias_backend:/code/competencias_backend
      - ./testes:/code/testes

  db:
    image: postgres:14.4-alpine
    container_name: db
    user: postgres
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev
    healthcheck:
      test: ["CMD", "pg_isready", "-q"]

volumes:
  postgres_data: